name: Jest CI
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Install dependencies
        run: npm install
      - name: Run Jest
        run: npm run test
